name: main 

on: 
  push:
    branches:
      - main

jobs: 

  test-infra: 
    runs-on: ubuntu-latest 
    timeout-minutes: 2
    steps: 
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
      - name: Install boto 3
        run: |
          pip install boto3
      - name: Install moto
        run: |
          pip install moto 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run unittests 
        run: |
          ls
          cd cloud-resume-challenge/lambdas/
          ls
          python test_get_function.py
          python test_put_function.py
          cd ..
          ls


  build-infra: 
      needs: test-infra 
      runs-on: ubuntu-latest
      steps: 
      - uses: actions/checkout@v3 
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
      - name: Install boto 3
        run: |
          pip install boto3
      - name: Install moto
        run: |
          pip install moto 
      - name: Build SAM
        run: sam build  
        working-directory: cloud-resume-challenge
      - name: Deploy 
        # Prevent prompts and failure when the stack is unchanged
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset
        working-directory: cloud-resume-challenge 


  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: oab-crc-website
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: cloud-resume-challenge/resume-site
